Add Pagination to Evolving Conditions Table (#225)
NCAR/music-box-interactive-client pull request #227
Opened 2024-01-09 16:27 UTC by ketansahugit

## Pull Request Summary

This pull request addresses issue #225 

### Changes Made

- Added pagination to the evolving conditions table on the 'Evolving' tab.
- Implemented the ability to configure the number of items shown per page.

Closes #225

2024-01-09 17:55 UTC, K20shores requested changes
Well done! I tested it out and it seems to work flawlessly; I left two comments. One related to styling, and another to use the react bootstrap components for pagination.

As it stands, this PR is great! If you don't have time to address the comments, I completely understand, but I would like these changes if possible.

Either way, thank you so much for this contribution!

2024-01-09 18:00 UTC, K20shores commented on src/components/Conditions/EvolvingConditionsDetail.jsx
> +           </label>
Would it be possible to add some styling? Either some slight internal padding and rounded edges, or maybe using the [react bootstrap select component](https://react-bootstrap.netlify.app/docs/forms/select/).

2024-01-11 17:15 UTC, merged

2024-01-12 15:44 UTC, ketansahugit commented
@K20shores Hey, I was about to work on the changes you had suggested, why did you merge the PR?

2024-01-12 16:03 UTC, K20shores commented
@ketansahugit because I liked your work! 

I would like the changes I asked for, but I also felt bad asking for them since you're doing this work of your own volition. Feel free to make those changes if you feel inclined and submit another PR though!