bugfixes for network graph
NCAR/music-box-interactive-client pull request #79
Opened 2023-05-30 19:31 UTC by jacobian-bacon

2023-05-30 19:37 UTC, K20shores requested changes

2023-05-30 19:37 UTC, K20shores commented on generator/src/pages/flow_diagram.js
> +    // console.log(diagram);
Please remove any commented-out code and console logs

2023-05-30 22:06 UTC, mattldawson approved these changes
Looks great! A couple minor things that we could make separate issues for:

- the time filter start value doesn't seem to be editable
- the default maximum for the flux filter doesn't seem to be set to the actual maximum flux
- Is the submit button just needed until more of the plot generation is done on the client side?
- We might want the plot to not include any species by default or have an easy way to unselect all the species (e.g., for the third example)

2023-06-06 17:37 UTC, K20shores approved these changes

2023-06-06 17:37 UTC, merged